# 配置文件加密key 生产环境中可通过环境变量、命令行等形式进行设置
jasypt:
  encryptor:
    password: xboot

server:
  port: 8888
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://123.57.64.57:3306/dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: dev
    # Jasypt加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果) 以下解密结果为123456
#    password: ENC(F4B0s6u9xcDw3V+P0qC4CA==)
    password: QQ123
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    # Druid StatViewServlet配置
    druid:
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: root
        login-password: ENC(F4B0s6u9xcDw3V+P0qC4CA==)
        # IP白名单 多个逗号分隔
        allow:
        # IP黑名单
        deny:
  jpa:
    show-sql: true
    # 自动生成表结构
    generate-ddl: true
    hibernate:
      ddl-auto: update
  # 文件大小上传配置
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jackson:
    time-zone: GMT+8
    serialization:
      fail-on-empty-beans: false
#  boot:
#    admin:
#      # 修改上下文路径
#      context-path: /actuator/admin
#      client:
#        url: http://127.0.0.1:${server.port}/actuator/admin

# 忽略鉴权url
ignored:
  urls:
    - /actuator/**
    - /dictData/getByType/**
    - /common/**
    - /druid/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /account/login
    - /account/add

# Actuator
management:
  health:
    status:
      http-mapping:
        DOWN: 200
        OUT_OF_SERVICE: 200
        FATAL: 200
        UNKNOWN: 200
    # 暂未用到ES 关闭其健康检查
    elasticsearch:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator/
      exposure:
        include: '*'

# Swagger界面内容配置
swagger:
  title: MMtap API接口文档
  description: MMtap Api Documentation
  version: 1.0.0
  termsOfServiceUrl: http://www.imkzp.com
  contact:
    name: MMtap
    url: http://www.imkzp.com
    email: java_khan@126.com

# 日志
logging:
  # 输出级别
  level:
    root: info
  # 指定路径
  path: logs
  file:
    # 最大保存天数
    max-history: 7
    # 每个文件最大大小
    max-size: 5MB
debug: true